//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroniNedviz_Makarova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bronirovanie
    {
        public int BronID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DateGo { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Count { get; set; }
        public string Oplata { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Objects Objects { get; set; }
        public virtual Users Users { get; set; }
    }
}
