//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroniNedviz_Makarova
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrafikUborki
    {
        public int GrafikID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public string Worker { get; set; }
        public Nullable<System.DateTime> PeriodTime { get; set; }
    
        public virtual Objects Objects { get; set; }
    }
}
