//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroniNedviz_Makarova
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BroniNedviz_MakarovaEntities : DbContext
    {
        public static BroniNedviz_MakarovaEntities Context;

        public BroniNedviz_MakarovaEntities()
            : base("name=BroniNedviz_MakarovaEntities")
        {
        }

        public static BroniNedviz_MakarovaEntities GetContext()
        {
            if (Context == null)
                Context = new BroniNedviz_MakarovaEntities();
            return Context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bronirovanie> Bronirovanie { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<GrafikUborki> GrafikUborki { get; set; }
        public virtual DbSet<Objects> Objects { get; set; }
        public virtual DbSet<OwnersObjects> OwnersObjects { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<StatusObject> StatusObject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
