//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroniNedviz_Makarova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objects()
        {
            this.Bronirovanie = new HashSet<Bronirovanie>();
            this.GrafikUborki = new HashSet<GrafikUborki>();
        }
    
        public int ObjectID { get; set; }
        public string Address { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string CategoryObject { get; set; }
        public Nullable<int> StatusObject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bronirovanie> Bronirovanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrafikUborki> GrafikUborki { get; set; }
        public virtual OwnersObjects OwnersObjects { get; set; }
        public virtual StatusObject StatusObject1 { get; set; }
    }
}
